const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Json,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Browser.Exps.QueryParam,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.AJAX.Exps.LastStatusCode,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.SetTimeout,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.Browser.Acts.Reload,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.JavaScriptInEvents.EventSheetHome_Event51_Act1,
		C3.Plugins.System.Acts.SetLayerEffectEnabled
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{Touch: 0},
	{AJAX: 0},
	{Browser: 0},
	{Tween: 0},
	{logo: 0},
	{text_welcome: 0},
	{wheel: 0},
	{Sine: 0},
	{logo_spin: 0},
	{pin: 0},
	{instruction_button: 0},
	{from: 0},
	{delay: 0},
	{targetX: 0},
	{cloud: 0},
	{button_spin: 0},
	{gray_background: 0},
	{instruction: 0},
	{button_got_it: 0},
	{prize_result: 0},
	{cat: 0},
	{button_back_to_home: 0},
	{flag: 0},
	{Audio: 0},
	{mute: 0},
	{confetti: 0},
	{JSON: 0},
	{loading_animation: 0},
	{text_something_went_wrong: 0},
	{button_try_again: 0},
	{group_logo: 0},
	{prizes: 0},
	{winningSector: 0},
	{sectorCount: 0},
	{isSpun: 0},
	{spinDuration: 0},
	{baseTurns: 0},
	{offset: 0},
	{target: 0},
	{language: 0},
	{isPlaySound: 0},
	{phone: 0},
	{name: 0},
	{apiBaseUrl: 0},
	{isFetching: 0},
	{isSpinning: 0},
	{isModalOpen: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	logo: class extends self.ISpriteInstance {},
	text_welcome: class extends self.ISpriteInstance {},
	wheel: class extends self.ISpriteInstance {},
	logo_spin: class extends self.ISpriteInstance {},
	pin: class extends self.ISpriteInstance {},
	instruction_button: class extends self.ISpriteInstance {},
	cloud: class extends self.ISpriteInstance {},
	button_spin: class extends self.ISpriteInstance {},
	gray_background: class extends self.ISpriteInstance {},
	instruction: class extends self.ISpriteInstance {},
	button_got_it: class extends self.ISpriteInstance {},
	prize_result: class extends self.ISpriteInstance {},
	cat: class extends self.ISpriteInstance {},
	button_back_to_home: class extends self.ISpriteInstance {},
	flag: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	mute: class extends self.ISpriteInstance {},
	confetti: class extends self.ISpriteInstance {},
	JSON: class extends self.IJSONInstance {},
	loading_animation: class extends self.ISpriteInstance {},
	text_something_went_wrong: class extends self.ISpriteInstance {},
	button_try_again: class extends self.ISpriteInstance {},
	group_logo: class extends self.ISpriteInstance {}
}